### PR TITLE
Add support for vim8 terminal

### PR DESCRIPTION
**Pull request by liquidz**
As the title says.

Vim8's `term_start` has a `term_finish` option, so `bclose.vim` is not required.

### CODE REVIEW

**Comment by maxigit** [comment]
What is the point of this feature ???? I've just upgraded to the last version of this plugin and nothing work anymore.
I understand this can be  desirable for some people (even though why just not launch tig in a vim terminal then ) but would that be possible to at least be able disable this feature ?

**Comment by iberianpig** [comment]
@maxigit 
Thanks for your comment!

Vim 8.1 terminal support to launch Tig from a Vim with a split-screen.

[Image from Gyazo](https://gyazo.com/b284af2e88082a05b01837fa924cf4f3)

Please tell me your Vim version and you are using and detail of the bug( if you can take gif animation or logs).

**Comment by liquidz** [comment]
FYI: If vim doesn't have a `terminal` feature, it should work as before.
https://github.com/iberianpig/tig-explorer.vim/pull/15/files#diff-a314566c10fdaf8ab29a5cfc9e8db2e5R177

**Comment by maxigit** [comment]
My vim has a terminal feature but I don't want to use it (not for tig at least)
I use Vim 8.2.128. There is no bug as such, just the fact that I don't get the same tig experience in vim terminal than in a normal buffer. First it looks differently, and it's really ugly. Then and this is the main problem, when I use tig I don't juse j and k but the up and down cursor. For some reasons, when I use the cursor keys on a terminal window , instead of sending them to the application it exit the insert mode and move the cursor. Every time I'm trying to type something I get  `E21: Cannot make changes, 'modifiable' is off`. Then I try every keys combination to exit and I'm stuck there. 

I think we just need an option to let the user chose if he wants to use vim terminal or just tig.

**Comment by iberianpig** [comment]
@maxigit 
I'm using Vim 8.2.128, but I haven't had the problem.
If you can provide a minimal .vimrc that reproduces the problem, I'd able to look up the problem for your help.

However, I'm in favor of adding this option, and I think that it's easy to add toggle flag to use built-in terminal (default value = true).
If you are OK, could you make the pull request?

**Comment by maxigit** [comment]
There is no problem as such (apart from the fact that I don't like vim
terminal and don't want to use it).
I'll do a pull request.

Any idea about how to name this option ?

**Comment by iberianpig** [comment]
Thank you!👍👍
How about let g:tig_explorer_use_builtin_term?

**Pull request merged**
